name: echo stuff

on:
  pull_request:
    types: [opened]

jobs:
  echo-from-different-repo:
    runs-on: ubuntu-latest
    name: A job to echo something from the composite action
    steps:
      - uses: jackaitken/github-actions-test/test-echo-something@v3
        with:
          message: "Mr. Watson come here I want to see you."
          name: "Thomas Watson"
