name: echo stuff

on:
  pull_request:
    types: [opened]

jobs:
  echo-from-different-repo:
    runs-on: ubuntu-latest
    name: A job to echo something from the composite action
    steps:
      - uses: jackaitken/github-actions-test/test-echo-something@v1
        with:
          message: "Hello from the other side"
          name: "Adele"
